import type { Plugin, ResolvedConfig, ViteDevServer } from "vite";
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";

export interface DialogsPluginOptions {
  /**
   * Absolute path to the directory that contains dialog components.
   */
  dir: string;
  /**
   * RegExp used to identify dialog component files.
   * Defaults to files whose name ends with `Dialog.vue` or `Drawer.vue`.
   */
  pattern?: RegExp;
  /**
   * Project-root-relative path for the generated TypeScript declaration file.
   * Defaults to `"src/dialogs.d.ts"`.
   */
  dts?: string;
}

const VIRTUAL_ID = "virtual:dialogs";
const RESOLVED_VIRTUAL_ID = "\0virtual:dialogs";

export function dialogsPlugin(options: DialogsPluginOptions): Plugin {
  const {
    dir,
    pattern = /(Dialog|Drawer)\.vue$/,
    dts = "src/dialogs.d.ts",
  } = options;

  let config: ResolvedConfig;

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  function scanFiles(): string[] {
    try {
      return readdirSync(dir)
        .filter((f: string) => pattern.test(f))
        .sort()
        .map((f: string) => resolve(dir, f));
    } catch {
      return [];
    }
  }

  function componentName(filePath: string): string {
    return basename(filePath, ".vue");
  }

  /**
   * Converts an absolute file path to an `@/`-prefixed import specifier,
   * given that `@` maps to `{root}/src`.
   */
  function toAliasImport(filePath: string): string {
    const srcRoot = resolve(config.root, "src");
    const rel = relative(srcRoot, filePath).replace(/\\/g, "/");
    return `@/${rel}`;
  }

  // ---------------------------------------------------------------------------
  // Code generation
  // ---------------------------------------------------------------------------

  function generateModuleCode(files: string[]): string {
    const lines: string[] = [
      `import { createApp } from "vue";`,
      `import { dialogControllerKey } from "@anfo/vite-dialogs-plugin/runtime";`,
    ];
    for (let i = 0; i < files.length; i++) {
      lines.push(
        `import _D${i} from ${JSON.stringify(toAliasImport(files[i]))};`,
      );
    }
    lines.push(`
function mountDialog(component, props) {
  const result = new Promise((resolve) => {
    const host = document.createElement("div");
    document.body.appendChild(host);
    let settled = false;
    function cleanup() { app.unmount(); host.remove(); }
    function finish(cb) {
      if (settled) return;
      settled = true;
      cb();
      cleanup();
    }
    function handleResolve(...args) {
      finish(() => {
        if (args.length === 0) { resolve({ type: "resolve" }); return; }
        resolve({ type: "resolve", value: args[0] });
      });
    }
    const controller = {
      resolve: handleResolve,
      reject: (reason) => { finish(() => resolve({ type: "reject", reason })); },
    };
    const app = createApp(component, props);
    app.provide(dialogControllerKey, controller);
    app.mount(host);
  });
  return Object.assign(result, {
    resolve(callback) {
      result.then((value) => {
        if (value.type === "resolve") callback?.(value.value);
      });
      return this;
    },
    reject(callback) {
      result.then((value) => {
        if (value.type === "reject") callback(value.reason);
      });
      return this;
    },
  });
}`);
    lines.push("");
    lines.push("export const dialogs = {");
    for (let i = 0; i < files.length; i++) {
      lines.push(
        `\t${componentName(files[i])}: (props) => mountDialog(_D${i}, props),`,
      );
    }
    lines.push("};");
    return lines.join("\n");
  }

  function generateDts(files: string[]): string {
    const dtsAbsPath = resolve(config.root, dts);
    const dtsDir = dirname(dtsAbsPath);

    // Compute relative path from the dts output dir to the runtime types file.
    // Using a relative path avoids bare-specifier resolution and TypeScript
    // path-alias interference (e.g. projects that alias "@" to "src/").
    const runtimeAbsPath = resolve(__dirname, "runtime");
    let runtimeRel = relative(dtsDir, runtimeAbsPath).replace(/\\/g, "/");
    if (!runtimeRel.startsWith(".")) runtimeRel = `./${runtimeRel}`;

    const lines: string[] = [
      "// Auto-generated by vite-plugin-dialogs — do not edit manually.",
      "",
      `declare module "${VIRTUAL_ID}" {`,
      `\ttype _C = import("vue").Component;`,
      `\ttype _CE<T extends _C> = import("vue-component-type-helpers").ComponentExposed<T>;`,
      `\ttype _CP<T extends _C> = import("vue-component-type-helpers").ComponentProps<T>;`,
      `\ttype _DE<T> = import("${runtimeRel}").DialogExposed<T>;`,
      `\ttype _DS<T> = import("${runtimeRel}").DialogSettledResult<T>;`,
      `\ttype _DR = import("${runtimeRel}").DialogRejectedResult;`,
      `\ttype _IK = "key" | "ref" | "ref_for" | "ref_key" | "class" | "style" | \`on\${string}\`;`,
      `\ttype _P<T extends _C> = Omit<_CP<T>, _IK>;`,
      `\ttype _RK<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K }[keyof T];`,
      `\ttype _A<T extends _C> = [_RK<_P<T>>] extends [never] ? [props?: _P<T>] : [props: _P<T>];`,
      `\ttype _V<T extends _C> = _CE<T> extends _DE<infer R> ? R : void;`,
      `\ttype _R<T extends _C> = _DS<_V<T>>;`,
      `\ttype _RN = _DR["reason"];`,
      `\ttype _H<T extends _C> = Promise<_R<T>> & {`,
      `\t\tresolve(callback?: (value: _V<T> | undefined) => void): _H<T>;`,
      `\t\treject(callback: (reason: _RN) => void): _H<T>;`,
      `\t};`,
      `\texport const dialogs: {`,
    ];

    for (const filePath of files) {
      const name = componentName(filePath);
      let rel = relative(dtsDir, filePath).replace(/\\/g, "/");
      if (!rel.startsWith(".")) rel = `./${rel}`;
      const comp = `typeof import(${JSON.stringify(rel)})["default"]`;
      lines.push(`\t\t${name}: (...args: _A<${comp}>) => _H<${comp}>;`);
    }

    lines.push("\t};", "}", "");
    return lines.join("\n");
  }

  // ---------------------------------------------------------------------------
  // .d.ts writer
  // ---------------------------------------------------------------------------

  function writeDts(): void {
    const dtsAbsPath = resolve(config.root, dts);
    mkdirSync(dirname(dtsAbsPath), { recursive: true });
    writeFileSync(dtsAbsPath, generateDts(scanFiles()), "utf-8");
  }

  // ---------------------------------------------------------------------------
  // Hot-reload helper
  // ---------------------------------------------------------------------------

  function invalidate(server: ViteDevServer): void {
    const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
    if (mod) server.moduleGraph.invalidateModule(mod);
    writeDts();
    server.hot.send({ type: "full-reload" });
  }

  // ---------------------------------------------------------------------------
  // Plugin
  // ---------------------------------------------------------------------------

  return {
    name: "vite-plugin-dialogs",

    configResolved(resolved) {
      config = resolved;
    },

    buildStart() {
      writeDts();
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID;
    },

    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return;
      return { code: generateModuleCode(scanFiles()), moduleType: "js" };
    },

    configureServer(server) {
      server.watcher.add(dir);

      server.watcher.on("add", (file) => {
        if (pattern.test(file) && file.startsWith(dir)) {
          invalidate(server);
        }
      });

      server.watcher.on("unlink", (file) => {
        if (pattern.test(file) && file.startsWith(dir)) {
          invalidate(server);
        }
      });
    },
  };
}
